# Generated by Django 5.2.7 on 2025-12-13 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='profile.profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='profile.profile'),
        ),
        migrations.AddField(
            model_name='story',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='profile.profile'),
        ),
        migrations.AddField(
            model_name='storyview',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_view', to='profile.story'),
        ),
        migrations.AddField(
            model_name='storyview',
            name='view_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_stories', to='profile.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('profile', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together={('story', 'view_profile')},
        ),
    ]
