# Generated by Django 5.2.7 on 2025-12-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='status',
            new_name='status_delete',
        ),
    ]
