# Generated by Django 5.2.7 on 2025-12-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='public_id',
            field=models.PositiveIntegerField(db_index=True, null=True, unique=True),
        ),
    ]
