# Generated by Django 5.2.7 on 2025-12-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_rename_status_story_status_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='status_delete',
            new_name='expired',
        ),
    ]
