# Generated by Django 5.2.7 on 2025-12-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_follow_status_alter_follow_following_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Follow', 'verbose_name_plural': 'Follows'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(db_index=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='follow',
        ),
    ]
