# Generated by Django 5.2.7 on 2025-11-16 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='private_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_messages', to='chats.privatechat'),
        ),
        migrations.AddField(
            model_name='privatechatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_stories', to='chats.profile'),
        ),
        migrations.AddField(
            model_name='story',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_stories', to='chats.profile'),
        ),
    ]
