# Generated by Django 5.2.7 on 2025-11-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='privatechatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='story',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='story',
            name='viewers',
        ),
        migrations.DeleteModel(
            name='PrivateChat',
        ),
        migrations.DeleteModel(
            name='PrivateChatMessage',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
