# Generated by Django 5.2.7 on 2025-10-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('active_role', models.CharField(blank=True, choices=[('Shifokor', 'Shifokor'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin'), ('Bemor', 'Bemor'), ('Klinika', 'Klinika'), ('PharmCompany', 'PharmCompany'), ('MedBrat', 'MedBrat'), ('Menejer', 'Menejer')], default='Shifokor', max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'db_table': 'custom_user',
                'ordering': ['id'],
            },
        ),
    ]
