# Generated by Django 5.2.7 on 2025-12-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'Phone Number'), ('email', 'Email')], max_length=100, null=True),
        ),
    ]
