# Generated by Django 5.2.7 on 2025-12-13 20:40

import apps.users.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.JSONField(blank=True, default=apps.users.choices.default_roles, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(blank=True, choices=[('Shifokor', 'Shifokor'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin'), ('FOYDALANUVCHI', 'FOYDALANUVCHI'), ('Klinika', 'Klinika'), ('PharmCompany', 'PharmCompany'), ('MedBrat', 'MedBrat'), ('Menejer', 'Menejer')], default='FOYDALANUVCHI', max_length=100, null=True),
        ),
    ]
