# Generated by Django 5.2.7 on 2025-11-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('ERKAK', 'Erkak'), ('AYOL', 'Ayol')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(choices=[('Shifokor', 'Shifokor'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin'), ('FOYDALANUVCHI', 'FOYDALANUVCHI'), ('Klinika', 'Klinika'), ('PharmCompany', 'PharmCompany'), ('MedBrat', 'MedBrat'), ('Menejer', 'Menejer')], default='FOYDALANUVCHI', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/image/'),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
