# Generated by Django 5.2.7 on 2025-12-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_registration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='_type',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('change-password', 'Change Password')], max_length=50, null=True),
        ),
    ]
