# Generated by Django 5.2.7 on 2025-11-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_gender_alter_customuser_active_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
