# Generated by Django 5.2.7 on 2025-11-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_smscode_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smscode',
            old_name='type',
            new_name='_type',
        ),
        migrations.AddField(
            model_name='smscode',
            name='update_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('ERKAK', 'Erkak'), ('AYOL', 'Ayol')], null=True),
        ),
    ]
