# Generated by Django 5.2.7 on 2025-11-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_type_smscode__type_smscode_update_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smscode',
            options={'ordering': ['-id'], 'verbose_name': 'Sms Code', 'verbose_name_plural': 'Sms Codes'},
        ),
        migrations.AlterModelTable(
            name='smscode',
            table='sms_code',
        ),
    ]
