# Generated by Django 5.2.7 on 2025-11-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='resend_code',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
