# Generated by Django 5.2.7 on 2025-11-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_smscode_resend_code_alter_smscode_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscode',
            name='update_verified',
        ),
        migrations.AddField(
            model_name='smscode',
            name='delete_obj',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
